Cargo.toml, src/lib.rs
Add a new crate feature `serde` to `Cargo.toml` and implement the features `serde::Serialize` and `serde::Deserialize` for all data structures. This is implementing the [C-SERDE](https://rust-lang.github.io/api-guidelines/interoperability.html#c-serde) requirement from the Rust API Guidelines. 
Fixes #7
Any other comments or notes.
=> Implement `serde::{Serialize, Deserialize}` for all data structures.

src/lib.rs
Implemented `sqrt()` function for quaternions. A few minor other improvements. 
Issue #9
=> Implemented `sqrt()`

src/lib.rs
Added the function `UnitQuaternion<T>::to_rotation_matrix3x3`. 
Issue #42
=> Implemented `to_rotation_matrix3x3`.

src/lib.rs
Fixes #51
Fixed: Quaternion<T>::norm() returns inaccurate results for very large and very small norms
Fixes #51
=> Fix norm inaccuracies. 

src/lib.rs
This pull request adds the implementation and tests for the `expf()` function. The `expf()` function raises a quaternion to a real power. It handles special cases such as zero, infinity, and NaN values. The implementation follows the specified conventions for boundary values and accurately determines the direction of the output quaternion. The tests cover various scenarios, including zero and infinity bases, negative bases, NaN quaternion components, and infinite quaternion components.
Issue #9
=> Implement and test expf() function

src/lib.rs
The methods that change the orientation of their rotation are:
- `rotate_vector`
- `to_rotation_matrix3x3`
- `from_rotation_matrix3x3`
This change was done to align better with commonly used conventions, in particular with the conventions and formulas used on Wikipedia.
None.
=> Change orientation convention of some UniqQuaternion methods.

README.md, src/lib.rs
The pull request removes a redundant link in the first paragraph of the README.md file and in the top-level documentation of the lib.rs file. The link was considered a distraction for newcomers and can be found further down in the README.md and lib.rs files with a clearer description.
None
=> Remove redundant link in README and lib.rs

src/lib.rs
Functions that don't belong together are now separated into different impl blocks. This is a pure refactoring. It improves the aesthetics of the code and the documentation.
None
=> Split `impl` blocks.

src/lib.rs
This new function provides the same functionality as `into_quaternion`. The name `into_inner` is more idiomatic, yet `into_quaternion` may be more clear in some contexts. That is why both functions are justified.
None
=> Provide `into_inner` method for `UnitQuaternion<T>`.

src/lib.rs
This pull request adds two new methods, `has_nan` and `is_all_nan`, to the codebase. The `has_nan` method checks if any component of a quaternion is `NaN`, while the `is_all_nan` method checks if all components of a quaternion are `NaN`. Additionally, tests have been added to ensure the correctness of these methods.
None
=> Add `has_nan` and `is_all_nan` methods and tests

src/lib.rs
This pull request includes several commits that improve the documentation and tests for the quaternion library. 
* The commits "Improve docs of `fast_norm`" and "Improve docs of `normalize`" enhance the documentation for these functions. 
* The commit "Wrote a line of documentation for many tests" adds documentation for multiple tests. 
* The commits "Improved test for norm of subnormal quaternions" and "Added new test for very large norm values" improve the tests for the norm of quaternions. 
* The commit "Split `test_normalize_zero_infinity_nan` into 3 tests" refactors the test for normalizing quaternions. 
* The commits "Added methods `has_nan` and `is_all_nan`" and "Added tests for `has_nan` and `is_all_nan`" introduce new methods and tests for checking NaN values. 
* The commit …
=> Improve documentation and tests for quaternion library

src/lib.rs
Changed an `assert` to `debug_assert`. in regular code apart from tests, the `assert` macro should generally not be used, but the `debug_assert` macro should be used instead. This PR fixes a violation of that rule. 
None
=> Changed an `assert` to `debug_assert`

.gitignore, ci/test_coverage_llvm.sh, ci/test_coverage_tarpaulin.sh
This pull request adds scripts for test coverage using `cargo-tarpaulin` and `llvm-cov-14`. The `.gitignore` file is also updated to include profiling file patterns. These scripts allow for generating test coverage data and displaying it in a readable format.
Fixes #18
=> Add test coverage scripts

src/lib.rs
This pull request fixes a bug in the `Quaternion::ln` method that caused incorrect handling of an edge case. Tests were added, one of which is triggered by the bug. The test coverage of `Quaternion::ln` is now at 100%. :)
None.
=> Fix edge case bug in Quaternion::ln

src/lib.rs
This pull request adds two test cases for the `Quaternion::sqrt()` function. The first test case covers the scenario where the real part is negative and the imaginary part has a subnormal norm. The second test case covers the scenario where the square norm of the input quaternion overflows to +infinity. These test cases ensure that the `Quaternion::sqrt()` function behaves correctly in these edge cases.
None
=> Add test cases for Quaternion::sqrt()

src/lib.rs
The pull request fixes bugs in the gimbal lock cases of the `to_euler_angles` function. The previous implementation had issues with calculating the correct pitch, roll, and yaw angles when encountering gimbal lock situations. The fix ensures that the correct angles are calculated in these cases. The pull request also includes additional test cases for gimbal lock scenarios to validate the fix.
None
=> Fix gimbal lock cases in to_euler_angles function

src/lib.rs
This pull request adds documentation and test cases for the `UnitQuaternion::from_rotation_vector` function. The documentation now mentions that the function may not be accurate for input vectors with a very large norm, and that if the input vector contains an infinite or `NaN` component, the result will be filled with `NaN`. The test cases cover scenarios with infinite and `NaN` inputs, ensuring the expected behavior of the function.
The results for infinite and `NaN` inputs are checked.
None.
=> Add documentation and test cases for UnitQuaternion::from_rotation_vector

Cargo.toml, ci/test_full.sh, src/lib.rs
This pull request adds a new feature called `rand` to `Cargo.toml` and the ci tests. It also includes the implementation of a uniform random distribution of `UnitQuaternion`s. The `UniformUnitQuaternion` struct allows sampling from this distribution by calling the `sample` method. The pull request also includes tests to ensure that the sample distribution of unit quaternions is uniform.
Fixes # 83
=> Add random sampling of UnitQuaternions

src/lib.rs
Introducing the extra type `UniformUnitQuaternion` did not add any value. It's clear from the usual use of `rand::distributions::Standard` that it means uniform distribution for `UnitQuaternion<T>`. This pull request removes the `UniformUnitQuaternion` type and replaces it with the `Standard` type for `rand::distributions::Distribution<UnitQuaternion<T>>`.
Related issue: #83
=> Remove own type `UniformUnitQuaternion` in favor of using `Standard`

ci/test_coverage_llvm.sh, src/lib.rs
This pull request activates all features for test coverage. It includes the addition of a randomized test called `test_to_rotation_from_rotation`. The test verifies the conversion from a unit quaternion to a 3x3 matrix and back in a randomized manner. 
Issue #89
=> Improve test coverage of `from_rotation_matrix3x3`

src/lib.rs
Test coverage showed that the test `test_unit_quaternion_inv_func` tested the `Inv` trait, but not the `inv()` method of `UnitQuaernion`.
Issue #89
=> Fixed test which tested the wrong function.

src/lib.rs
This pull request adds new test cases for 100% coverage of the `UnitQuaternion::from_two_vectors` function. The test cases cover scenarios where the vectors are opposite and perpendicular, as well as randomized cases. The goal is to ensure that the function behaves correctly in all scenarios.
Issue #89
=> Add test cases for UnitQuaternion::from_two_vectors

src/lib.rs
This is the last remaining function which was not covered by tests. Now all functions and all lines of code are covered by tests. Code which is not fully covered is only in debug assertions and standard derive macros.
Fixes #89
=> Added a test for the unstable function `from_euler_angles_struct`.

src/lib.rs
Added test for the function `Quaternion::normalize` with subnomal norm.
I tried to improve test coverage as measured by `tarpaulin`. Unfortunately, the coverage did not improve, but the test is still useful. It looks like the coverage is not accurately measured by `tarpaulin`, unfortunately. Manually checking the output of `ci/test_coverage_llvm.sh` shows that lines of executable code in `lib.rs` are fully covered by tests. 
Issue #89
=> Added test for the function `Quaternion::normalize` with subnomal norm.

examples/pose_animation.rs
This pull request simplifies the example output by implementing the `Display` trait for `CameraPose`. This allows for cleaner and more concise printing of pose information, reducing code duplication in the main function. The output format remains unchanged, ensuring consistency in the displayed results.
None.
=> Removed duplication in example.

src/quaternion.rs, src/unit_quaternion.rs
This pull request introduces the `one()` methods for both `Quaternion` and `UnitQuaternion`, providing a convenient way to obtain the real unit quaternion. Additionally, examples have been added to all functions in the `unit_quaternion` module to enhance documentation and usability. These changes aim to improve the clarity and functionality of the quaternion library.
Issue #8
=> Add `one()` methods and examples for `Quaternion` and `UnitQuaternion`

RELEASES.md, ci/test_coverage_llvm.sh
The `test_coverage_llvm.sh` script has been extended to allow the use of command line parameters `--filter` and `--check`. The `--filter` parameter shows only the uncovered lines to the user, while the `--check` parameter verifies that the test coverage did not change. Additionally, the script's inline documentation has been improved. In addition to the script changes,  `RELEASES.md` has been updated to include the missing contributor info.
None
=> Extend test_coverage_llvm.sh script and add missing contributors

README.md, src/lib.rs, src/quaternion.rs, src/unit_quaternion.rs
This pull request updates the documentation for the `Quaternion` struct. It adds information about the interop with the `serde` and `rand` crates, including how to serialize or deserialize `Quaternion`s with `serde` and how to randomly sample `UnitQuaternion`s using the `rand` crate. Additionally, it mentiones in the top-level docs the new functions of the `Quaternion` struct, such as `fast_norm` and transcendental functions. The documentation also mentions methods for conversion between `UnitQuaternion` and 3x3 matrices.
Fixed #106
=> Update Quaternion documentation with interop details

examples/pose_animation.rs
This pull request adds a detailed explanation of spherical linear interpolation (slerp) and linear interpolation of individual euler angles in the pose_animation example. The explanation highlights the differences between the two methods and the potential artifacts that can occur with euler angle interpolation. It also includes a link to a 3Blue1Brown video that provides further insights into quaternions and 3D rotation.
Fixes #106
=> Add detailed explanation of slerp and euler angles in pose_animation example

Cargo.toml
The `num-integer` crate, a dependency of `num-quaternion`, by default sets the `std` feature on `num-traits`, which causes `std` to be incorporated into the build... which isn't good if one is trying to use `num-quaternion` in a `#[no_std]` environment. This pull request stops that from happening.
N/A
=> Stop num-integer dependency pulling in std by default

.github/workflows/cargo_build_and_test.yml, Cargo.toml, RELEASES.md, benches/norm_runtime.rs, ci/rustup.sh, ci/test_coverage_llvm.sh
`criterion::black_box` is deprecated in the latest version of the `criterion` crate. It hints that `std::hint::black_box` should be used instead, which we do in this PR. This in turn requires the Rust version 1.66.0 where the feature was stabilized. Thus I updated the minimum supported Rust version to 1.66.0. 
None. 
(If an item is not applicable, please check it anyway.)
=> Fix deprecated use of `criterion::black_box`. 

Cargo.toml, RELEASES.md, benches/c++/.bazelrc, benches/c++/BUILD.bazel, benches/c++/from_rotation_vector_runtime.cpp, benches/from_rotation_vector_runtime.rs, examples/chebyshev_approximation.rs, src/unit_quaternion.rs
Introduce polynomial approximations for `sinc(sqrt(x))` and `cos(sqrt(x))`. These are used to optimize `from_rotation_vector()` for `f32` precision. Added benchmarks to evaluate performance against the previous implementation and other packages. 
Fixes #121
(If an item is not applicable, please check it anyway.)
=> Implement polynomial approximations and benchmarks for rotation vectors
